### ISSUE TITLE
[Feature] Memory extraction

### ISSUE THREAD

**Issue by 0xroot-bf** [nccgroup/LazyDroid#1]
Cool tool! Something that might be interesting to implement is memory extracting through Frida, though this might require to have frida-server running as root in the device, and probably a rooted device (not sure if that's under scope).

Something similar to this: https://github.com/Nightbringer21/fridump
It's an universal memory extraction utility built at top of Frida.  Ideal for performing memory dumping and inspect for secrets if the application does not handle the memory in a secure way.

A different approach could be done with the procmem utility built for Android platforms.

**Comment by dan1t0** [comment]
Thank for your feedback @0xroot, I will try to research this feature to include it in future releases,

Cheers
