### ISSUE TITLE
[enhancement] change gnome-terminal to x-terminal-emulator

### ISSUE THREAD

**Issue by eclipse95** [nccgroup/LazyDroid#2]
Hi,
In the "change me" variables, you can change `gnome-terminal` to `x-terminal-emulator`.
With this tweak, `lazyDroid.sh` can work on every graphical environment using X.org.

**Comment by dan1t0** [comment]
Hi @eclipse95 , thank you for your time.

I just tried "x-terminal-emulator" and it did not work for me in ubuntu.

Cheers

**Comment by dan1t0** [comment]
hi, I just tried "x-terminal-emulator" and it did not work for me in ubuntu.

Cheers

**Comment by eclipse95** [comment]
Hi @dan1t0,
I have also experienced some problems too. I replaced ``x-terminal-emulator`` by ``xfce4-terminal``, but it didn't work better. Moreover, ``x-terminal-emulator --help`` shows ``xfce4-terminal``'s help. 

So the problem is somewhere else. I will try to investigate.

**Comment by eclipse95** [comment]
Hi @dan1t0,
After some tests, xfce4-terminal doesn't like ``-e "command1|command2"``. 
``x-terminal-emulator -e 'bash -c "command1|command2";exec $SHELL'`` can fix the problem.

This fix is ugly but it works.

**Comment by eclipse95** [comment]
Hi @dan1t0,
I found a fix for the problem we have experienced.
Normally, it should work better now.
