### ISSUE TITLE
Something might be broken

### ISSUE THREAD

**Issue by securisec** [nccgroup/LazyDroid#5]
Hey looks like something might have broken in a new push ... getting two errors that I wasnt getting before. 

- ---> Something was wrong trying to sign the app. Press Enter to continue
- ---> ERROR: Can't find file {dirpath}...Main.smali

**Comment by eclipse95** [comment]
Hi @securisec,
Could you try to use [my master branch of my fork](https://github.com/eclipse95/LazyDroid) ? 
My repo doesn't the last PR #4.
I am trying to fix your problem in another branch.
